#!/usr/bin/env bash

# Settings
DEBIAN_VERSION="12"
DEBIAN_VERNAME="bookworm"
DEBIAN_RELEASE="20240201-1644"
DEBIAN_VARIANT="genericcloud-amd64"

GIT_CACHE_NAME="debian-$DEBIAN_VERSION-$DEBIAN_VARIANT-$DEBIAN_RELEASE"
GIT_CACHE_PATH="*.qcow2"

# Image settings
# IMAGE_ADDR="https://cloud.debian.org/images/cloud"
# IMAGE_TYPE="genericcloud"
# IMAGE_ARCH="amd64"
# IMAGE_FILE="debian-$DEBIAN_VERSION-$IMAGE_TYPE-$IMAGE_ARCH-$DEBIAN_RELEASE.qcow2"
# IMAGE_PATH="$IMAGE_ADDR/$DEBIAN_VERNAME/$DEBIAN_RELEASE/$IMAGE_FILE"

# Export variables to github workflow next steps
cat >> "$GITHUB_ENV" <<-EOF
	DEBIAN_VERSION="$DEBIAN_VERSION"
	DEBIAN_VERNAME="$DEBIAN_VERNAME"
	DEBIAN_RELEASE="$DEBIAN_RELEASE"
	DEBIAN_VARIANT="$DEBIAN_VARIANT"
	GIT_CACHE_NAME="$GIT_CACHE_NAME"
	GIT_CACHE_PATH="$GIT_CACHE_PATH"
EOF

# wget "https://cloud.debian.org/images/cloud/$DEBIAN_VERNAME/$DEBIAN_RELEASE/debian-${DEBIAN_VERSION}-${DEBIAN_VARIANT}-${DEBIAN_RELEASE}.qcow2"

# echo "---1"
# echo "$@"
# echo "---2"
