#!/usr/bin/env bash

# Debian
DEBIAN_VERSION="12"
DEBIAN_VERNAME="bookworm"
DEBIAN_RELEASE="20240201-1644"
DEBIAN_VARIANT="genericcloud-amd64"
DEBIAN_BASEURL="https://cloud.debian.org/images/cloud"
DEBIAN_FILEURL="$DEBIAN_BASEURL/$DEBIAN_VERNAME/$DEBIAN_RELEASE/debian-${DEBIAN_VERSION}-${DEBIAN_VARIANT}-${DEBIAN_RELEASE}.qcow2"

# Image filename
IMAGE_FILENAME=$(basename $DEBIAN_FILEURL)

# Github cache
GIT_CACHE_NAME="debian-$DEBIAN_VERSION-$DEBIAN_VARIANT-$DEBIAN_RELEASE"

# Export variables to github workflow
if [[ -f "$GITHUB_ENV" ]]; then
cat >> "$GITHUB_ENV" <<-EOF
	DEBIAN_VERSION=$DEBIAN_VERSION
	DEBIAN_VERNAME=$DEBIAN_VERNAME
	DEBIAN_RELEASE=$DEBIAN_RELEASE
	DEBIAN_VARIANT=$DEBIAN_VARIANT
	DEBIAN_FILEURL=$DEBIAN_FILEURL
	IMAGE_FILENAME=$IMAGE_FILENAME
	GIT_CACHE_NAME=$GIT_CACHE_NAME
EOF
fi
