name: 'Smart Cache'
description: 'Cache artifacts like dependencies and build outputs to improve workflow execution time'
branding:
  icon: 'archive'
  color: 'purple'
runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        key: ${{ env.GIT_CACHE_NAME }}
        path: ${{ env.GIT_CACHE_PATH }}
      id: cache
