name: 'Smart Cache'
description: 'Cache artifacts like dependencies and build outputs to improve workflow execution time'
branding:
  icon: 'archive'
  color: 'purple'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        key: ${{ env.GIT_CACHE_NAME }}
        path: ${{ env.GIT_CACHE_PATH }}
      id: cache
    # - name: Set color
    #   id: color-selector
    #   run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"