name: Create release

on:
  workflow_call:
    inputs:
      debian-version:
        description: 'A Debian image version to be downloaded'
        default: '12'
      debian-vername:
        description: 'A Debian image version name to be downloaded'
        default: 'bookworm'
      debian-release:
        description: 'A Debian image release to be downloaded'
        default: '20240201-1644'
    
jobs:
  download:
    name: Download image
    runs-on: ubuntu-latest

    steps:
      - name: Cache image
        uses: actions/cache@v4
        id: cache
        with:
          key: debian-${{ inputs.debian-version }}-genericcloud-amd64-${{ inputs.debian-release }}.qcow2
          path: debian-${{ inputs.debian-version }}-genericcloud-amd64-${{ inputs.debian-release }}.qcow2
    
      - name: Download image
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          DEBIAN_VERSION: ${{ inputs.debian-version }}
          DEBIAN_VERNAME: ${{ inputs.debian-vername }}
          DEBIAN_RELEASE: ${{ inputs.debian-release }}
        run: |
          wget -O "debian-${DEBIAN_VERSION}-genericcloud-amd64-${DEBIAN_RELEASE}.qcow2" \
            "https://cloud.debian.org/images/cloud/${DEBIAN_VERNAME}/${DEBIAN_RELEASE}/debian-${DEBIAN_VERSION}-genericcloud-amd64-${DEBIAN_RELEASE}.qcow2"
