name: Create Release

on:
  workflow_call

jobs:
  release:
    runs-on: ubuntu-latest
    steps:  
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #
        run: echo "To be deleted!"
  #       run: |
  #         gh release create "${GITHUB_REF_NAME}" \
  #             --repo="${GITHUB_REPOSITORY}" \
  #             --title="${GITHUB_REF_NAME}" \
  #             --generate-notes \
  #             --latest \
  #             --draft
