name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*
      - debian*
  
permissions:
  contents: write

env:
  DEBIAN_VERSION: "12"
  DEBIAN_VERNAME: "bookworm"
  DEBIAN_RELEASE: "20240201-1644"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:  
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "To be deleted!"
  #       run: |
  #         gh release create "${GITHUB_REF_NAME}" \
  #             --repo="${GITHUB_REPOSITORY}" \
  #             --title="${GITHUB_REF_NAME}" \
  #             --generate-notes \
  #             --latest \
  #             --draft

  download:
    name: Download image
    runs-on: ubuntu-latest

    steps:
      - name: Cache image
        uses: actions/cache@v4
        id: cache
        with:
          key: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
          path: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
    
      - name: Download image
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          IMAGE_FILENAME: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
        run: wget -O "$IMAGE_FILENAME" "https://cloud.debian.org/images/cloud/$DEBIAN_VERNAME/$DEBIAN_RELEASE/$IMAGE_FILENAME"

          # wget -O "debian-${DEBIAN_VERSION}-genericcloud-amd64-${DEBIAN_RELEASE}.qcow2" \
          #   "https://cloud.debian.org/images/cloud/${DEBIAN_VERNAME}/${DEBIAN_RELEASE}/debian-${DEBIAN_VERSION}-genericcloud-amd64-${DEBIAN_RELEASE}.qcow2"

  rebuild-cloud-image:
    name: Rebuild cloud image
    runs-on: ubuntu-latest
    needs:
      # - release
      - download

    steps:
      - name: Cache image
        uses: actions/cache@v4
        id: cache
        with:
          key: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
          path: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
      
      - name: to-be-deleted
        run: echo "To be deleted!"

      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Install libguestfs
      #   run: |
      #     sudo apt-get update -y
      #     sudo apt-get install -y libguestfs-tools

      # - name: Download image
      #   run: |
      #     source settings.sh
      #     wget -O "$IMAGE_FILE" "$IMAGE_PATH"

      # - name: Build image
      #   run: |
      #     echo "cloudimage" > build.log
      #     cat README.md

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: debian-cloudimage
      #     path: build.log
      #     retention-days: 1

  # publish-cloudimage:
  #   runs-on: ubuntu-latest
  #   needs: build-cloudimage

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: debian-cloudimage

  #     - name: Publish image
  #       run: |
  #         cat build.log
  #         cat README.md

  rebuild-docker-image:
    name: Rebuild docker image
    runs-on: ubuntu-latest
    needs:
      # - release
      - download

    steps:
      - name: Cache image
        uses: actions/cache@v4
        id: cache
        with:
          key: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
          path: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
      
      - name: to-be-deleted
        run: echo "To be deleted!"


  upload-cloud-image:
    name: Upload cloud image
    runs-on: ubuntu-latest
    needs:
      - release
      - rebuild-cloud-image

    steps:      
      - name: to-be-deleted
        run: echo "To be deleted!"
        
  upload-docker-image:
    name: Upload docker image
    runs-on: ubuntu-latest
    needs:
      - release
      - rebuild-docker-image

    steps:      
      - name: to-be-deleted
        run: echo "To be deleted!"
