name: Release

on:
  push:
    tags:
      - v*
      - debian*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${GITHUB_REF_NAME}" \
              --generate-notes \
              --latest \
              --draft

  build-cloudimage:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          echo "cloudimage" > build.log
          cat README.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-cloudimage
          path: build.log
          retention-days: 1

  publish-cloudimage:
    runs-on: ubuntu-latest
    needs: build-cloudimage

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: debian-cloudimage

      - name: Publish image
        run: |
          cat build.log
          cat README.md

      
