name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${GITHUB_REF_NAME}" \
              --generate-notes \
              --latest \
              --draft
