name: Release

on:
  push:
    tags:
      - v*
      - debian*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${GITHUB_REF_NAME}" \
              --repo="${GITHUB_REPOSITORY}" \
              --title="${GITHUB_REF_NAME}" \
              --generate-notes \
              --latest \
              --draft

  build:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          echo "Build done" > build.log
          cat README.md

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish image
        run: |
          cat README.md
          cat build.log

      
