name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - debian*
  
permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  DEBIAN_VERSION: "12"
  DEBIAN_VERNAME: "bookworm"
  DEBIAN_RELEASE: "20240201-1644"
  IMAGE_FILENAME: "debian-12-genericcloud-amd64-20240201-1644.qcow2"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:  
      - name: Create release draft
        run: echo "To be deleted!"
  #       run: |
  #         gh release create "${GITHUB_REF_NAME}" \
  #             --repo="${GITHUB_REPOSITORY}" \
  #             --title="${GITHUB_REF_NAME}" \
  #             --generate-notes \
  #             --latest \
  #             --draft

  download:
    name: Download image
    runs-on: ubuntu-latest
    steps:
      - id: cache
        name: Cache image
        uses: actions/cache@v4
        with:
          key: ${{ env.IMAGE_FILENAME }}
          path: ${{ env.IMAGE_FILENAME }}
    
      - name: Download image
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget -O "$IMAGE_FILENAME" \
            "https://cloud.debian.org/images/cloud/$DEBIAN_VERNAME/$DEBIAN_RELEASE/$IMAGE_FILENAME"

  rebuild-cloud-image:
    name: Rebuild cloud image
    needs: [release, download]
    runs-on: ubuntu-latest

    steps:
      - name: Cache image
        uses: actions/cache/restore@v4
        with:
          key: ${{ env.IMAGE_FILENAME }}
          path: ${{ env.IMAGE_FILENAME }}

      - name: Install libguestfs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libguestfs-tools

      - name: Rebuild image
        run: |
          sudo virt-customize -a "debian-${DEBIAN_VERSION}-genericcloud-amd64-${DEBIAN_RELEASE}.qcow2" \
            --install qemu-guest-agent \
            --install locales-all \
            --install htop
        
      - name: Upload artifacts
        run: |
          gh release upload "debian-${DEBIAN_VERSION}-${DEBIAN_RELEASE}" "*.qcow2"

  rebuild-docker-image:
    name: Rebuild docker image
    needs: [release, download]
    runs-on: ubuntu-latest

    steps:
      - name: Cache image
        uses: actions/cache/restore@v4
        with:
          key: ${{ env.IMAGE_FILENAME }}
          path: ${{ env.IMAGE_FILENAME }}

      - name: Install libguestfs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libguestfs-tools

      - name: Rebuild image
        run: |
          sudo virt-customize -a "*.qcow2" \
            --install qemu-guest-agent \
            --install locales-all \
            --install htop
        
      - name: Upload artifacts
        run: |
          gh release upload "debian-${DEBIAN_VERSION}-${DEBIAN_RELEASE}" "*.qcow2"
