name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*
      - debian*
  
permissions:
  contents: write

env:
  DEBIAN_VERSION: "12"
  DEBIAN_VERNAME: "bookworm"
  DEBIAN_RELEASE: "20240201-1644"

  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:  
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "To be deleted!"
  #       run: |
  #         gh release create "${GITHUB_REF_NAME}" \
  #             --repo="${GITHUB_REPOSITORY}" \
  #             --title="${GITHUB_REF_NAME}" \
  #             --generate-notes \
  #             --latest \
  #             --draft

  download:
    name: Download image
    runs-on: ubuntu-latest
    steps:
      - name: Cache image
        uses: actions/cache@v4
        id: cache
        with:
          key: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
          path: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
    
      - name: Download image
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          IMAGE_FILENAME: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
        run: wget -O "$IMAGE_FILENAME" "https://cloud.debian.org/images/cloud/$DEBIAN_VERNAME/$DEBIAN_RELEASE/$IMAGE_FILENAME"

          # wget -O "debian-${DEBIAN_VERSION}-genericcloud-amd64-${DEBIAN_RELEASE}.qcow2" \
          #   "https://cloud.debian.org/images/cloud/${DEBIAN_VERNAME}/${DEBIAN_RELEASE}/debian-${DEBIAN_VERSION}-genericcloud-amd64-${DEBIAN_RELEASE}.qcow2"

  rebuild-cloud-image:
    name: Rebuild&Upload cloud image
    needs: [release, download]
    runs-on: ubuntu-latest

    steps:
      - name: Cache image
        uses: actions/cache/restore@v4
        with:
          key: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
          path: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2

      - name: Install libguestfs
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libguestfs-tools

      - name: Build image
        run: |
          sudo virt-customize -a "$debian-${DEBIAN_VERSION}-genericcloud-amd64-${DEBIAN_RELEASE}.qcow2" \
            --install qemu-guest-agent \
            --install locales-all \
            --install htop
        
      - name: Upload artifacts
        run: |
          # run: gh release upload "${GITHUB_REF_NAME}" "${IMAGE_FILE}"
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          gh release upload "debian-${DEBIAN_VERSION}-${DEBIAN_RELEASE}" \
            "$debian-${DEBIAN_VERSION}-genericcloud-amd64-${DEBIAN_RELEASE}.qcow2"

  rebuild-docker-image:
    name: Rebuild&Upload docker image
    needs: [release, download]
    runs-on: ubuntu-latest

    steps:
      - name: Cache image
        uses: actions/cache/restore@v4
        id: cache
        with:
          key: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
          path: debian-${{ env.DEBIAN_VERSION }}-genericcloud-amd64-${{ env.DEBIAN_RELEASE }}.qcow2
        
