name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Download original Debian qcow2 image
  download:
    name: Download image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load settings
        run: source settings.sh

      - id: cache
        name: Cache
        uses: ./.github/actions/smart-cache

      - name: Download original image
        run: wget "$DEBIAN_FILEURL"
        if: steps.cache.outputs.cache-hit != 'true'

  # Customize images
  customize:
    name: Customize image
    needs: download
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [qemu, locales, extras]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load settings
        run: source settings.sh

      - name: Load cached files
        uses: ./.github/actions/smart-cache

      - name: Install libguestfs
        run: |
          # sudo apt-get update -y
          # sudo apt-get install -y libguestfs-tools

      - name: Rebuild image
        run: ./customize.sh ${{ env.IMAGE_FILENAME }} ${{ matrix.variant }}

      - name: Compress image artifact
        run: ./compress.sh ${{ env.IMAGE_FILENAME }} ${{ matrix.variant }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}
          retention-days: 1

  # Release
  release:
    name: Create release
    needs: customize
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load settings
        run: source settings.sh

      - name: Load cached files
        uses: ./.github/actions/smart-cache

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - run: ls -lh

      # - name: Create release draft
      #   uses: ./.github/actions/create-release
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

      # - name: Upload original image artifact
      #   run: gh release upload "${GITHUB_REF_NAME}" *.qcow2
      #   if: startsWith(github.ref, 'refs/tags/')

      # - name: Upload custom image artifact
      #   run: gh release upload "${GITHUB_REF_NAME}" *.qcow2

      - run: echo "### Finished! :rocket:" >> $GITHUB_STEP_SUMMARY

  xpto:
    name: Upload artifacts
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
