name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - v*
      - debian*

permissions:
  contents: write

jobs:
  # Release
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Create release draft
        run: ./builder.sh release

  # Download
  download:
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: echo Download

      - name: Test 1
        run: echo $DEBIAN_RELEASE

      - name: Test 2
        run: ./builder.sh aaa 111

      - name: Test 3
        run: echo $DEBIAN_RELEASE

      - name: Test 4
        run: echo ${{ env.DEBIAN_RELEASE }}

      - name: Test 5
        run: ./builder.sh bbb 222
