name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Release
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    name: Create release
    runs-on: ubuntu-latest

    # steps:
      # - uses: actions/checkout@v1
      #   name: Checkout
      # - uses: ./.github/actions/automatic-tests
      #   name: Test

      # - uses: actions/checkout@v4
      # - name: Create release draft
      #   run: |
      #     gh release create "${GITHUB_REF_NAME}" \
      #       --repo="${GITHUB_REPOSITORY}" \
      #       --title="${GITHUB_REF_NAME}" \
      #       --verify-tag \
      #       --latest \
      #       --draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release draft
        uses: ./.github/actions/create-release

      # - uses: actions/create-release@latest
      # - uses: ubimetrics/github-actions/create-release@latest
      # - uses: ./.github/actions/create-release

  # Download
  download:
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: echo Download

      - name: Test 1
        run: echo $DEBIAN_RELEASE

      - name: Test 2
        run: ./builder.sh aaa 111

      - name: Test 3
        run: echo $DEBIAN_RELEASE

      - name: Test 4
        run: echo ${{ env.DEBIAN_RELEASE }}

      - name: Test 5
        run: ./builder.sh bbb 222
