name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - v*
      - debian*

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Release
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Create release draft
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --repo="${GITHUB_REPOSITORY}" \
            --verify-tag \
            --latest \
            --draft

  # Download
  download:
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        run: echo Download

      - name: Test 1
        run: echo $DEBIAN_RELEASE

      - name: Test 2
        run: ./builder.sh aaa 111

      - name: Test 3
        run: echo $DEBIAN_RELEASE

      - name: Test 4
        run: echo ${{ env.DEBIAN_RELEASE }}

      - name: Test 5
        run: ./builder.sh bbb 222
