name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Release
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    name: Create release
    runs-on: ubuntu-latest

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4

    #   - name: Create release draft
    #     uses: ./.github/actions/create-release

    steps:
      - name: Create release draft
        uses: ubimetrics/test/.github/actions/create-release@${{ github.ref }}

  # Download
  download:
    name: Download
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Cache image
      #   uses: actions/cache@v4
      #   with:
      #     key: "debian-${{ env.DEBIAN_VERSION }}-${{ env.DEBIAN_VARIANT }}-${{ env.DEBIAN_RELEASE }}"
      #     path: "*.qcow2"
      #   id: cache

      # - name: Download image
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: echo Downloading file...
      #   #run: wget "https://cloud.debian.org/images/cloud/$DEBIAN_VERNAME/$DEBIAN_RELEASE/debian-${DEBIAN_VERSION}-${DEBIAN_VARIANT}-${DEBIAN_RELEASE}.qcow2"

      # - name: Upload original image artifact
      #   run: gh release upload "${GITHUB_REF_NAME}" *.qcow2
